In [ ]:
import numpy as np

version

In [ ]:
np.__version__

'1.23.5'

# **scalar is 0 dimensional,  vector is 1 dimensional, matrix is 2 dimensional, tensor is 3 dimensional, so square brackets will be used according to the dim no. like vecot [   ] , matrix [[    ]] , tensor [[[      ]]] .**

# **scalar**

In [ ]:
a= np.array(20)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

20
1
()
0
int64


# **vector**

In [ ]:
b= np.array([1,2,3,4,5])
print(b)
print(b.size)
print(b.shape)
print(b.ndim)
print(b.dtype)
print(len(b))
type(b)

[1 2 3 4 5]
5
(5,)
1
int64
5


numpy.ndarray

# **Matrix**

Note: if column wise no of elements does not match then c will be considered as object instead of matrix, also any other type can be given instaed of numerics in matrix which will be considered as object or string instead of matrix, in this kind of scenarios it will not throw any errors.

In [ ]:
c= np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)
print(c.size)
print(c.shape)
print(c.ndim)
print(c.dtype)
print(len(c))
type(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
2
int64
3


numpy.ndarray

# **Tensor**

Note: The shape of matrix in tensor should be the same.

Reshape: reshape the type into specified format. reshape(row,col) axis 0 is no of rows, axis 1 is no of columns


reshape(no.of matrix,rows,columns)

arange(start element , end-1 element , elements jump with the range)

In [ ]:
d=np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(d)
print(d.reshape(3,3,1))
print(d.size)
print(d.shape)
print(d.ndim)
print(d.dtype)
print(len(d))
type(d)


d1=np.arange(1,37).reshape(3,3,4)
print(d1)






e= np.arange(1,13).reshape(4,3)
print(e)
print(e.shape[0])
f= np.arange(1,13).reshape(1,-1) # we can use np.newaxis instead of reshape in this statement
print(f)
print ("arange")
f1= np.arange(1,13)
print(f1)
print("newaxis")
print(f1[ : ,np.newaxis])
f2= np.arange(1,13).reshape(-1,1)
print(f2)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]
[[[1]
  [2]
  [3]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]
9
(1, 3, 3)
3
int64
1
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
4
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
arange
[ 1  2  3  4  5  6  7  8  9 10 11 12]
newaxis
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


## **Multiplication**

In [ ]:
a1=np.array([[1,2],[3,4],[5,6]])
a2=np.array([[7,8],[9,0],[0,1]])
a3=np.array([[1,2,3],[4,5,6]])
print(a1)
print(a2)
print(a3)
print(a1*a2)
a4=np.dot(a1,a3)
print(a4)

[[1 2]
 [3 4]
 [5 6]]
[[7 8]
 [9 0]
 [0 1]]
[[1 2 3]
 [4 5 6]]
[[ 7 16]
 [27  0]
 [ 0  6]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


# **Broadcasting**


For Machine Learning : y=mx+c

In [ ]:
b1=np.array([[1,2],[3,4],[5,6]])
print(b1)
b2=np.array([2,2])
print(b2)
print(b1+b2)
b3=np.array([[1,2],[1,2],[1,2]])
print(b1+b3)
b4=np.array([[1],[2],[3]])
print(b1+b4)
b5=np.array([[3],[3],[3]])
print(b1+b5)



[[1 2]
 [3 4]
 [5 6]]
[2 2]
[[3 4]
 [5 6]
 [7 8]]
[[2 4]
 [4 6]
 [6 8]]
[[2 3]
 [5 6]
 [8 9]]
[[4 5]
 [6 7]
 [8 9]]


# **Stacking**

np.vstack , np.hstack  = vertical and horizontal stacking

In [ ]:
c1=np.array([[1,2],[3,4],[5,6]])
print(c1,'\n\n')
c2=np.array([2,2])
print(c2, '\n\n\n\n')
print(np.vstack([c1,c2]),'\n\n\n')
c3=np.array([3,3])
print(np.hstack([c3,c2]))


[[1 2]
 [3 4]
 [5 6]] 


[2 2] 




[[1 2]
 [3 4]
 [5 6]
 [2 2]] 



[3 3 2 2]


# **Axis wise sum,mean,max,min operations in Matrix**

np.zeros(1,3) , np.ones(3,3) - this all gives matrix with zeros and ones

np.where - conditional operation on elements in matrix

In [ ]:
d1=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(np.sum(d1,axis=0))
print(np.sum(d1,axis=1))
print(np.sum(d1,axis=1,keepdims=True))
print(np.where(d1>3,d1**2,d1))

[ 9 12 15]
[ 6 12 18]
[[ 6]
 [12]
 [18]]
[[ 1  2  3]
 [ 3 16 25]
 [25 36 49]]


In [ ]:
np.eye(3)  # identical matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Slicing**

In [ ]:
s=np.arange(1,13).reshape(3,4)
print(s,'\n\n\n')
print(s[ 0 , :], '\n\n')
print(s[0:2 , 1:4],'\n\n')
print(s[-2:,-2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 



[1 2 3 4] 


[[2 3 4]
 [6 7 8]] 


[[ 7  8]
 [11 12]]


# **Linspace** **and Meshgrid**

linspace(starting from, ending to , how many points needed in output)

In [ ]:
l1=np.linspace(-5,5,5)
print(l1)
l2=np.linspace(-5,5,5)
print(l2)

[-5.  -2.5  0.   2.5  5. ]
[-5.  -2.5  0.   2.5  5. ]


In [ ]:
x,y=np.meshgrid(l1,l2)
print(x,'\n\n\n')
print(y)

[[-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]] 



[[-5.  -5.  -5.  -5.  -5. ]
 [-2.5 -2.5 -2.5 -2.5 -2.5]
 [ 0.   0.   0.   0.   0. ]
 [ 2.5  2.5  2.5  2.5  2.5]
 [ 5.   5.   5.   5.   5. ]]
